### ISSUE TITLE
Default terrain generated with multiverse

### ISSUE THREAD

**Issue by Erudition** [nvx/CleanroomGenerator#16]
On a 1.6.4 mcpc server I have multiverse and I tried to make a Cleanroom that is NOT my default world.
 However,
**/mvcreate Origin -g CleanroomGenerator**
or my preferred:
**/mcreate Origin -t flat -g CleanroomGenerator:.**
...both generate default terrain.
CleanroomGenerator shows up in **/mv gens**.

**Comment by nvx** [comment]
Closing due to age.
