### ISSUE TITLE
enderdragon cleanroom

### ISSUE THREAD

**Issue by Lucifer-Angels** [nvx/CleanroomGenerator#18]
the enderdragon keeps re-spawning along with the portal every time my server restarts
and im using cleanroom void in an end dimension for a project when every time i come back a masive chunk of my build is destroyed and core protect wont fix it using rollbacks or restores

**Comment by nvx** [comment]
I'm not quite sure what the behaviour you're after is.

If you're after disabling mob spawning or protecting the world from mob griefing, that functionality is out of scope of this plugin.

If there's a feature request or bug in scope (world generation related) that I've missed, please feel free to re-open this issue.
