### ISSUE TITLE
World Generation Issue

### ISSUE THREAD

**Issue by wherkamp** [nvx/CleanroomGenerator#19]
https://imgur.com/a/ekd2fca
This was my command
/mvcreate ocean normal -g CleanroomGenerator:9|stone|3|dirt|7|sand|9|water

**Comment by wherkamp** [comment]
I am guessing it was a Spigot bug. I updated and reran it. World gen was nice.

**Comment by nvx** [comment]
Sounds like this is no longer an issue. Feel free to re-open if that's not the case.
