### ISSUE TITLE
update to 1.14.4 API 

### ISSUE THREAD

**Issue by Tsoccerguy3** [nvx/CleanroomGenerator#22]
update to spigot API 1.14.4
update names . example grass is now minecraft:grass_block

**Comment by Tsoccerguy3** [comment]
On 1.14.4 using Multiverse-core 4.1 and CleanroomGenerator , I get 1 bedrock 2 dirt 1 grass , with this Multiverse entry . I should get 1 bedrock and 20 water . I have worldborder plugin and trimed cunks back to the border and then issued a /wb fill , command and got flat grass . The only thing i can think of is that 1.13 is very different than 1.14.4  api and so cleanroom gets ignored

SancityRevival:
    ==: MVWorld
    hidden: 'false'
    alias: SancityRevival
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -984.5
      y: 5.0
      z: -389.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '-2466819008911170254'
    generator: CleanroomGenerator:20|minecraft:water
    playerLimit: '-1'
    allowFlight: 'true'

**Comment by nvx** [comment]
Can you try with v1.1.1 at https://dev.bukkit.org/projects/cleanroomgenerator/files/3073918?

**Comment by nvx** [comment]
Closing old issue - assume fixed in v1.1.1 and later.
