### ISSUE TITLE
CleanroomGenerator Existing World gerneration issue

### ISSUE THREAD

**Issue by JanaFischinger** [nvx/CleanroomGenerator#23]
Hello

I have a big problem and hope somebody can help me.
on my server i created a flat world a few years ago with:
/mvcreate test normal -g CleanroomGenerator:20,stone,8,dirt,1,grass

And today when i walk in a new area i got some 16x16 blocks:
https://imgur.com/7nTUNnn

how can it fix this

**Comment by Tsoccerguy3** [comment]
If this is on 1.14.4 , the plugin is not working and needs a update . Also start using the new block names.
ie .. from multiverse config
generator: CleanroomGenerator:2|minecraft:dirt|1|minecraft:grass_block

**Comment by Tsoccerguy3** [comment]
latest version
https://github.com/Multiverse/Multiverse-Core/tree/4.1.0

the generator line gets added in the config for each world or you can add manually

generator: CleanroomGenerator:20|minecraft:stone|8|minecraft:dirt|1|minecraft:grass_block

**Comment by nvx** [comment]
Please try with v1.1.1 of the plugin.
