### ISSUE TITLE
Stone_bricks

### ISSUE THREAD

**Issue by gruniu8** [nvx/CleanroomGenerator#26]
i cant use command "/mvcreate flatworld normal -g CleanroomGenerator:40,stone_bricks"
it's my problem or plugin? and i was trying to put . somewhere to dont have bedrock but idk where

**Comment by gruniu8** [comment]
nevermind, | should be :

**Comment by gruniu8** [comment]
btw i'm playing on newest version of plugin on 1.16
paperMC (this paper spigot bukkit engine)

**Comment by nvx** [comment]
Needs to be | not , and I'm not sure if just stone_bricks is good enough or if it needs to be the full minecraft:stone_bricks name.

If you want no bedrock too you'd want this `/mvcreate flatworld normal -g CleanroomGenerator:.40|minecraft:stone_bricks`

**Comment by nvx** [comment]
I'm going to close this old issue as I assume your lack of response means you've gotten it working. Feel free to re-open if that's not the case.
