### ISSUE TITLE
Option to generate blocks at Y -64 for 1.18 world height.

### ISSUE THREAD

**Issue by JasonTable** [nvx/CleanroomGenerator#28]
Currently when creating a cleanroom dimension in 1.18, the layers start stacking at Y 0. This differs from the Minecraft Superflat behavior in 1.18 which is to generate the bedrock at Y -64 and stack layers up from there because of the height limit change.

For the sake of backwards compatibility with older worlds, it should probably stay the way it is right now. However I propose a method of telling the plugin to start stacking the layers at Y -64 instead.

Maybe a special character can be used at the start of the generation string. Like how the "." makes bedrock not spawn. Maybe another character like "^" or something could be used at the start of the string to make blocks generate at Y -64. For example, to make a classic flat world the same way vanilla 1.18 does, something like

`CleanroomGenerator:^2|dirt|1|grass_block`

Could be used. and it can be combined with the dot for worlds to generate without bedrock. something like

`CleanroomGenerator:^.1|barrier` or `CleanroomGenerator:.^1|barrier`

That would make a world with just a layer of barrier at Y -64.

**Comment by nvx** [comment]
That sounds like a great option, and supporting both `^.` and `.^` ordering would reduce confusion.

Unfortunately I haven't opened Minecraft in years, but I'd be more than happy to merge in a PR if you're inclined to implement it. I must admit for such a simple plugin I'm amazed it still gets used after all these years!

**Comment by HammerWizrd** [comment]
I would very much like to see this as an update to the generator since trying to go into negatives only returns an error and sets generation to the default 64|stone. Especially since the new update changes spawn rates the deeper you go and farmworlds would be much more efficient if the base was able to go that low!
![image](https://user-images.githubusercontent.com/49102678/148224993-f344dd78-9ad9-4080-a1dc-91fb5d7bfa3d.png)

**Comment by JasonTable** [comment]
A few weeks ago I created pull request #29 that adds my feature request. It has yet to be merged. Once its merged, the feature will be added. However if you would like to use it now, my version is available to download here https://github.com/JasonTable/CleanroomGenerator/releases

**Comment by nvx** [comment]
I've published v1.2.1 on CurseForge with this feature. Note it may take a little bit for it to be reviewed.

The only difference between this official release and the v1.2.0 @JasonTable published is that the official version is built using Java8 to match the minimum Java version Minecraft is built against, while JasonTable's version is built against Java17 which may cause issues if your server is running an older Java version.
