### ISSUE TITLE
Void genarator doesnt work

### ISSUE THREAD

**Issue by Josh65-2201** [nvx/CleanroomGenerator#32]
In the documentation it says use "CleanroomGenerator:^." to make a void but in 1.18 it doesnt work. Multiverse is accepting it and keeping it but going to an area with no chunks will start genrating terrain like normal.

**Comment by bop34** [comment]
can confirm I also have experienced this

**Comment by Josh65-2201** [comment]
I relased genarators with multiverse dont worked for the default world set in the server.properties.

**Comment by nvx** [comment]
Ah yeah if you want world generators for the default world you have to configure it in your bukkit.yml not MultiVerse.

https://bukkit.fandom.com/wiki/Bukkit.yml#*OPTIONAL*_worlds has some info and examples for reference.
